export default [
    {
        id: 0,
        name: 'The Astrodacadreon',
        position: {x: 0, y: 0, z: 0 },
        size: {x: 10, y: 10, z: 10 },
        trendingIndice: 10,
        mainColor: 0xe39700,
        mainImage: '', 
    },
    {
        id: 1,
        name: 'Alexander the Brave',
        position: {x: 100, y: 5, z: 0 },
        size: {x: 5, y: 5, z: 5 },
        trendingIndice: 4,
        mainColor: 0xe3b24f,
        mainImage: '', 
    },
    {
        id: 2,
        name: 'Cult of the blood Wolf',
        position: {x: 0, y: 5, z: 100 },
        size: {x: 3, y: 3, z: 3 },
        trendingIndice: 4,
        mainColor: 0x850505,
        mainImage: '', 
    },
    {
        id: 3,
        name: 'Dollye Pooe',
        position: {x: -100, y: 5, z: 0 },
        size: {x: 3, y: 3, z: 3 },
        trendingIndice: 4,
        mainColor: 0xf5edae,
        mainImage: '', 
    },
]